apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ttl-reaper.fullname" . }}-manager-role
  labels:
  {{- include "kube-ttl-reaper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - '*/finalizers'
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - '*/status'
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-ttl-reaper.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kube-ttl-reaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kube-ttl-reaper.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kube-ttl-reaper.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'