apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-ttl-reaper.fullname" . }}-controller-manager
  labels:
  {{- include "kube-ttl-reaper.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}